name: Build CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: node18-linux-x64
            output: tv-broadcast-linux
          - os: windows-latest
            target: node18-win-x64
            output: tv-broadcast-win.exe

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build CLI
      run: npx pkg index.js -o dist/cli/${{ matrix.output }} -t ${{ matrix.target }}
